import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Manrope, Roboto, Cormorant,   } from "next/font/google";
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const geistCormorant = Cormorant({
  weight: ["400", "500", "700"],
  variable: "--font-cormorant",
  subsets: ["vietnamese",],
});

const geistRoboto = Roboto({
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
  subsets: ["latin"],
});
const geistManrope = Manrope({
  weight: ["500", "600"],
  variable: "--font-manrope",
  subsets: ["greek"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${geistRoboto.variable}  ${geistManrope.variable}  ${geistCormorant.variable}`}>{children}</body>
    </html>
  );
}
  {/*className={inter.className}*/}
